### PR TITLE
Regenerate donate page if the nonprofit id doesn't exist 

### LINKED ISSUE #83: [DMS] Regenerate donate page if the nonprofit id doesn't exist
Currently, the donate page (`pages/donate/[id].tsx`) uses `getStaticPaths` to retrieve a list of nonprofit names at build time (when the website is deployed), and `getStaticProps` to pre-render donate pages for the nonprofits at build time. However, this means we need to manually re-build the website each time a new nonprofit onboards onto our website to generate the new donate page. Instead, we should attempt to rebuild the donate page for any nonprofit id and throw an error if the nonprofit id doesn't exist.

- [x] Look at the Next.js [docs on data fetching](https://nextjs.org/docs/basic-features/data-fetching) to understand how `getStaticPaths()` and `getStaticProps()` work together. Read about the [`fallback` property](https://nextjs.org/docs/basic-features/data-fetching#fallback-true) in detail - you should modify how it is being used in `pages/donate/[id].tsx` to complete this task.
- [x] Notice that the `getStaticProps()` method calls `getNonprofitById(id)` to retrieve the non-profit object from our DB. When `fallback` was set to `false`, we could be certain that a non-profit with  id=`id` existed in our DB. But now, Next.js won't render a 404 page by default for non-existant `id`s. So you must enclose this code in a `try-catch` to catch [run-time exceptions thrown by `getNonprofitById(id)`](https://github.com/GTBitsOfGood/gen-soln/blob/develop/server/actions/nonprofit.ts#L51) for non-existant `id`s.
- [x] In your `try` block, you can keep returning `props: { nonprofit, items, selectedValue: id }`, however, you will have to decide what you want to return in the `catch` block. You could return an empty object, `props: {}`, as a suggestion.
- [x] Now, we will have to deal with type changes. Since `NonprofitDonationPage` is no longer guaranteed to receive a `nonprofit` object from `getStaticProps()` every time, it's **incorrect** to say:
```javascript
const NonprofitDonationPage: NextPage<React.ComponentProps<typeof DonationPage >>
```
So first, let's modify our `getStaticProps` function signature to:
```javascript
// eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
export const getStaticProps = async (context: GetStaticPropsContext) => {
```
And we will modify the `NonprofitDonationPage` declaration to:
```javascript
const NonprofitDonationPage: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = props => {
```
This will tell TypeScript to infer the prop types of `NonprofitDonationPage` from the return type of `getStaticProps()`. You will have to import `GetStaticPropsContext`.
- [x] Now, in `NonprofitDonationPage`, we will have to [check if a fallback page](https://nextjs.org/docs/basic-features/data-fetching#fallback-pages) is being rendered. If it is, let's render `null` _(bonus points if you want to implement a loading component, like a simple header with loading text)._
- [x] If a fallback page isn't being rendered, check if the passed in `props` contain the `nonprofit` object and return the `DonationPage` component:
```javascript
if (props.nonprofit) {
  return <DonationPage {...props} />;
}
```
- [x] Below the above `if`, we will return 404 page UI. This UI is shown to users who visit `/donate/id` for a non-profit `id` that doesn't exist in our DB. You can use the `next/error` module for the 404 page UI, see: https://github.com/vercel/next.js/discussions/10960
- [x] Lastly, look into Next.js's incremental site generation: https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration feature. You will have to specify the `revalidate` property in `getStaticProps()` to avoid some weird UI bugs and behavior when using `fallback: true`; can you guess why?

### PR DESCRIPTION
**Pull request by ML-Chen**
Fixes #83 
Tested it with making new nonprofits in MongoDB Compass (with a string _id field) and it seems to work properly.

### CODE REVIEW

File: pages/donate/[id].tsx [hunk 1]
```diff
@@ -1,52 +1,68 @@
...
 
-const NonprofitDonationPage: NextPage<React.ComponentProps<
-  typeof DonationPage
->> = props => <DonationPage {...props} />;
+const NonprofitDonationPage: NextPage<InferGetStaticPropsType<
+  typeof getStaticProps
+>> = props => {
+  if (props.nonprofit) {
+    return <DonationPage {...props} />;
+  } else {
```
Comment (PC98) [inline pages/donate/[id].tsx:23]: nit: don't need the `else {`

File: pages/donate/[id].tsx [hunk 2]
```diff
@@ -1,52 +1,68 @@
...
-
 import config from "config";
 
-const NonprofitDonationPage: NextPage<React.ComponentProps<
-  typeof DonationPage
->> = props => <DonationPage {...props} />;
+const NonprofitDonationPage: NextPage<InferGetStaticPropsType<
+  typeof getStaticProps
+>> = props => {
+  if (props.nonprofit) {
```
Comment (PC98) [inline pages/donate/[id].tsx:21]: Don't forget to check for fallback! See: https://github.com/GTBitsOfGood/gen-soln/blob/develop/pages/events/%5Bid%5D.tsx#L18

File: pages/donate/[id].tsx [hunk 3]
```diff
@@ -1,52 +1,68 @@
...
 export const getStaticPaths: GetStaticPaths = async () => {
   const ids = await getNonprofitIds();
 
-  return { paths: ids.map(config.pages.donate), fallback: false };
+  return { paths: ids.map(config.pages.donate), fallback: true };
 };
 
-export const getStaticProps: GetStaticProps = async ({ params }) => {
-  const id = params?.id as string;
+export const getStaticProps = async (context: GetStaticPropsContext) => {
```
Comment (PC98) [inline pages/donate/[id].tsx:34]: Nit: add an eslint-disable-next-line to skip this warning

File: pages/donate/[id].tsx [hunk 4]
```diff
@@ -1,52 +1,68 @@
...
+      })
+    );
+
+    return {
+      props: {
+        nonprofit,
+        items,
+        selectedValue: id
+      },
+      revalidate: 10
```
Comment (PC98) [inline pages/donate/[id].tsx:58]: Question: do we know how to pick a value for revalidate? Is it just try and see what happens on prod? I think for `events/[id].tsx` we just picked 1 since that's what the example of Next.js' docs uses.

Comment (ML-Chen) [reply pages/donate/[id].tsx:58]: I don't know

File: pages/donate/[id].tsx (hunk 1 above)
Comment (ML-Chen) [reply pages/donate/[id].tsx:23]: Personally I prefer the explicit `else {` unless one branch of the if-else is much longer.

File: pages/donate/[id].tsx (hunk 2 above)
Comment (ML-Chen) [reply pages/donate/[id].tsx:21]: Is checking `props.nonprofit` not sufficient?

File: pages/donate/[id].tsx (hunk 4 above)
Comment (PC98) [reply pages/donate/[id].tsx:58]: ah okay it's fine then

**Review by PC98 — APPROVED** [review]
