### PR TITLE
Make checking for GET in fetchRequestWithPayloadResponse case-insensitive

### LINKED ISSUE #250: GET requests are broken for events requests
#230 tried to implement GET requests in `fetchRequestWithPayloadResponse`, but there's faulty logic.

We use `"get"` at the callsite, but checks for `"GET"` in the function so it always sends a POST.

### PR DESCRIPTION
**Pull request by migueldlr**
Closes #250

### CODE REVIEW

File: utils/util.ts [hunk 1]
```diff
@@ -56,7 +56,7 @@ export const fetchRequestWithPayloadResponse = async <T>(
   // eslint-disable-next-line @typescript-eslint/ban-types
   body: object = {}
 ): Promise<T> => {
-  const isGetRequest = options.method === "GET";
+  const isGetRequest = options.method?.toUpperCase() === "GET";
```
Comment (PC98) [inline utils/util.ts:59]: Do we want to make a similar change on line 23, or is that always correct set by Next.js?

**Review by PC98 — APPROVED** [review]

File: utils/util.ts (hunk 1 above)
Comment (migueldlr) [reply utils/util.ts:59]: Oop
